name: Deploy Experiment Index to Cloudflare Pages
on:
  push:
    branches:
      - main
    paths:
      - 'experiment_index/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy experiment_index --project-name=cse813-paas-experiments
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
