name: Service deployments

on:
  push:
    branches:
      - main
  workflow_dispatch: { }

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [ matrix_multiplication, n_even, nth_largest, user_registration, user_validation ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: ${{ matrix.service }}/**

      - name: Set up Docker Buildx
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta for tags and labels
        id: meta
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/cse813_paas_${{ matrix.service }}
          tags: |
            type=sha,format=short
            type=raw,value=latest

      - name: Build and push Docker image
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Render
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          SERVICE_NAME=${{ matrix.service }}
          SECRET_NAME="CSE813_PAAS_${SERVICE_NAME^^}_DEPLOY_HOOK"
          DEPLOY_URL="${!SECRET_NAME}"
          echo "Initiating deployment for $SERVICE_NAME."
          curl "$DEPLOY_URL"
          echo "Deployment initiated."
        env:
          CSE813_PAAS_NTH_LARGEST_DEPLOY_HOOK: ${{ secrets.CSE813_PAAS_NTH_LARGEST_DEPLOY_HOOK }}
          CSE813_PAAS_USER_REGISTRATION_DEPLOY_HOOK: ${{ secrets.CSE813_PAAS_USER_REGISTRATION_DEPLOY_HOOK }}
          CSE813_PAAS_USER_VALIDATION_DEPLOY_HOOK: ${{ secrets.CSE813_PAAS_USER_VALIDATION_DEPLOY_HOOK }}
          CSE813_PAAS_MATRIX_MULTIPLICATION_DEPLOY_HOOK: ${{ secrets.CSE813_PAAS_MATRIX_MULTIPLICATION_DEPLOY_HOOK }}
          CSE813_PAAS_N_EVEN_DEPLOY_HOOK: ${{ secrets.CSE813_PAAS_N_EVEN_DEPLOY_HOOK }}
